"""add payment_plan_id to transactions

Revision ID: 10716e6808f4
Revises: 2a8f5c4df4d1
Create Date: 2026-08-17 13:09:05.608811

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "10716e6808f4"
down_revision: Union[str, Sequence[str], None] = "2a8f5c4df4d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions", sa.Column("payment_plan_id", sa.UUID(), nullable=True)
    )
    op.create_index(
        op.f("ix_transactions_payment_plan_id"),
        "transactions",
        ["payment_plan_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_transactions_payment_plan_id_payment_plans"),
        "transactions",
        "payment_plans",
        ["payment_plan_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_transactions_payment_plan_id_payment_plans"),
        "transactions",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_transactions_payment_plan_id"), table_name="transactions")
    op.drop_column("transactions", "payment_plan_id")
    # ### end Alembic commands ###
