"""add auth providers and sessions

Revision ID: 18b64bcfbb3b
Revises: a13660e604b3
Create Date: 2026-08-11 10:17:39.983194

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18b64bcfbb3b"
down_revision: Union[str, Sequence[str], None] = "a13660e604b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_providers",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("local", "google", name="auth_provider_enum"),
            nullable=False,
        ),
        sa.Column("provider_user_id", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(provider = 'local'  AND password_hash IS NOT NULL "
            "AND provider_user_id IS NULL) OR "
            "(provider <> 'local' AND provider_user_id IS NOT NULL "
            "AND password_hash IS NULL)",
            name=op.f("ck_auth_providers_provider_fields"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_auth_providers_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_providers")),
        sa.UniqueConstraint(
            "provider", "provider_user_id", name="uq_provider_identity"
        ),
    )
    op.create_index(
        op.f("ix_auth_providers_user_id"), "auth_providers", ["user_id"], unique=False
    )
    op.create_index(
        "uq_auth_providers_local_per_user",
        "auth_providers",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("provider = 'local'"),
    )
    op.create_table(
        "sessions",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "revoked", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index(
        op.f("ix_sessions_refresh_token_hash"),
        "sessions",
        ["refresh_token_hash"],
        unique=True,
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_refresh_token_hash"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(
        "uq_auth_providers_local_per_user",
        table_name="auth_providers",
        postgresql_where=sa.text("provider = 'local'"),
    )
    op.drop_index(op.f("ix_auth_providers_user_id"), table_name="auth_providers")
    op.drop_table("auth_providers")
    # ### end Alembic commands ###

    # El create_table del ENUM lo crea implícitamente el primer create_table
    # que lo usa; drop_table NO lo elimina. Sin esto, un downgrade + upgrade
    # falla con "type auth_provider_enum already exists".
    op.execute("DROP TYPE IF EXISTS auth_provider_enum;")
