"""add payment plans table

Revision ID: 2a8f5c4df4d1
Revises: c75d7c8c91af
Create Date: 2026-08-17 12:45:17.198773

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a8f5c4df4d1"
down_revision: Union[str, Sequence[str], None] = "c75d7c8c91af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_plans",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("to_account_id", sa.UUID(), nullable=True),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column(
            "type",
            # transaction_type_enum ya existe en Postgres (lo creó la
            # migración de transactions). create_type=False evita el
            # CREATE TYPE duplicado.
            ENUM(  # type: ignore[reportUnknownArgumentType]
                "income",
                "expense",
                "transfer",
                name="transaction_type_enum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("next_due_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "is_recurring",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("frequency_interval", sa.Integer(), nullable=True),
        sa.Column(
            "frequency_unit",
            sa.Enum("day", "week", "month", "year", name="frequency_unit_enum"),
            nullable=True,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(type = 'transfer' AND to_account_id IS NOT NULL "
            "AND to_account_id != account_id) "
            "OR (type != 'transfer' AND to_account_id IS NULL)",
            name=op.f("ck_payment_plans_transfer_account"),
        ),
        sa.CheckConstraint(
            "type != 'transfer' OR category_id IS NULL",
            name=op.f("ck_payment_plans_transfer_no_category"),
        ),
        sa.CheckConstraint(
            "(is_recurring = TRUE AND frequency_interval IS NOT NULL "
            "AND frequency_unit IS NOT NULL) "
            "OR (is_recurring = FALSE AND frequency_interval IS NULL "
            "AND frequency_unit IS NULL AND end_date IS NULL)",
            name=op.f("ck_payment_plans_recurring_fields"),
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR end_date >= next_due_date",
            name=op.f("ck_payment_plans_end_date_after_due"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_payment_plans_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_payment_plans_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_payment_plans_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["to_account_id"],
            ["accounts.id"],
            name=op.f("fk_payment_plans_to_account_id_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_payment_plans_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_plans")),
    )
    op.create_index(
        op.f("ix_payment_plans_account_id"),
        "payment_plans",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        "ix_payment_plans_next_due_date",
        "payment_plans",
        ["next_due_date"],
        unique=False,
        postgresql_where=sa.text("is_active = true"),
    )
    # ### end Alembic commands ###
    op.execute(
        """
            CREATE TRIGGER trg_payment_plans_set_updated_at
                BEFORE UPDATE ON payment_plans
                FOR EACH ROW
                EXECUTE FUNCTION set_updated_at();
            """
    )
    op.execute(
        """
            CREATE OR REPLACE FUNCTION check_payment_plan_category_group()
            RETURNS TRIGGER AS $$
            DECLARE
                v_account_group  UUID;
                v_category_group UUID;
            BEGIN
                IF NEW.category_id IS NOT NULL THEN
                    SELECT group_id INTO v_account_group
                        FROM accounts WHERE id = NEW.account_id;
                    SELECT group_id INTO v_category_group
                        FROM categories WHERE id = NEW.category_id;
                    IF v_account_group IS DISTINCT FROM v_category_group THEN
                        RAISE EXCEPTION
                            'La categoría debe pertenecer al grupo de la cuenta.';
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
    )
    op.execute(
        """
            CREATE TRIGGER trg_check_payment_plan_category_group
                BEFORE INSERT OR UPDATE ON payment_plans
                FOR EACH ROW
                EXECUTE FUNCTION check_payment_plan_category_group();
            """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_payment_plans_next_due_date",
        table_name="payment_plans",
        postgresql_where=sa.text("is_active = true"),
    )
    op.drop_index(op.f("ix_payment_plans_account_id"), table_name="payment_plans")
    op.drop_table("payment_plans")
    # ### end Alembic commands ###
