"""add invitations table

Revision ID: 439d4ea2526c
Revises: 6dd14bedf6e6
Create Date: 2026-08-13 14:26:14.821568

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "439d4ea2526c"
down_revision: Union[str, Sequence[str], None] = "6dd14bedf6e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invitations",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("invited_by", sa.UUID(), nullable=True),
        sa.Column(
            "role",
            # role_enum ya existe en Postgres (lo creó la migración de
            # account_group_members). create_type=False evita el CREATE TYPE
            # duplicado — solo funciona con el ENUM de postgresql, el
            # sa.Enum genérico ignora ese parámetro en silencio.
            # El stub de postgresql.ENUM no propaga el tipo genérico de
            # Column como sí hace sa.Enum, así que pyright ve Column[Unknown].
            ENUM(  # type: ignore[reportUnknownArgumentType]
                "owner", "admin", "member", name="role_enum", create_type=False
            ),
            server_default=sa.text("'member'"),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "accepted", "expired", name="status_enum"),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("accepted_by", sa.UUID(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["accepted_by"],
            ["users.id"],
            name=op.f("fk_invitations_accepted_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["account_groups.id"],
            name=op.f("fk_invitations_group_id_account_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["users.id"],
            name=op.f("fk_invitations_invited_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitations")),
    )
    op.create_index(op.f("ix_invitations_code"), "invitations", ["code"], unique=True)
    op.create_index(
        op.f("ix_invitations_group_id"), "invitations", ["group_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invitations_group_id"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_code"), table_name="invitations")
    op.drop_table("invitations")
    # ### end Alembic commands ###
