"""add account_group_members table

Revision ID: 6dd14bedf6e6
Revises: b7b9caaed4c1
Create Date: 2026-08-12 12:32:23.676586

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6dd14bedf6e6"
down_revision: Union[str, Sequence[str], None] = "b7b9caaed4c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_group_members",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("owner", "admin", "member", name="role_enum"),
            server_default=sa.text("'member'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["account_groups.id"],
            name=op.f("fk_account_group_members_group_id_account_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_account_group_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_group_members")),
        sa.UniqueConstraint("group_id", "user_id", name="uq_group_member"),
    )
    op.create_index(
        op.f("ix_account_group_members_group_id"),
        "account_group_members",
        ["group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_group_members_user_id"),
        "account_group_members",
        ["user_id"],
        unique=False,
    )
    op.execute(
        """
                CREATE TRIGGER trg_account_group_members_set_updated_at
                    BEFORE UPDATE ON account_group_members
                    FOR EACH ROW
                    EXECUTE FUNCTION set_updated_at();
                """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_account_group_members_user_id"), table_name="account_group_members"
    )
    op.drop_index(
        op.f("ix_account_group_members_group_id"), table_name="account_group_members"
    )
    op.drop_table("account_group_members")
    # ### end Alembic commands ###
