"""create users table

Migración inicial: la tabla `users` y la infraestructura de `updated_at`.

La parte de `op.create_table` la generó `--autogenerate` a partir del modelo.
La función `set_updated_at()` y su trigger se añadieron a mano: Alembic solo
sabe leer lo que está declarado en los modelos de SQLAlchemy, y los triggers,
funciones e índices parciales no lo están. Todo eso se escribe con
`op.execute()`.

Sin el trigger, `updated_at` solo tendría el `server_default = NOW()`, que se
aplica una única vez en el INSERT: el valor se quedaría congelado en la fecha
de creación. Se resuelve en la base de datos y no con `onupdate` de SQLAlchemy
para que también cubra los UPDATE que no pasan por el ORM (una migración, un
script de mantenimiento, un psql a mano).

`set_updated_at()` es genérica y no menciona ninguna tabla: cada tabla nueva
con columna `updated_at` solo tiene que crear su propio trigger apuntando a
esta misma función.

Revision ID: a13660e604b3
Revises:
Create Date: 2026-08-10 14:17:22.574372

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a13660e604b3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at := NOW();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###

    op.execute(
        """
        CREATE TRIGGER trg_users_set_updated_at
            BEFORE UPDATE ON users
            FOR EACH ROW
            EXECUTE FUNCTION set_updated_at();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # DROP TABLE se lleva por delante sus propios triggers, así que no hace
    # falta borrar trg_users_set_updated_at explícitamente.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###

    # La función sí es independiente de la tabla y hay que borrarla aparte.
    op.execute("DROP FUNCTION IF EXISTS set_updated_at();")
