"""add categories table

Revision ID: b1a3876a0184
Revises: ec323ec5c6fc
Create Date: 2026-08-17 10:50:46.986340

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1a3876a0184"
down_revision: Union[str, Sequence[str], None] = "ec323ec5c6fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_categories_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["account_groups.id"],
            name=op.f("fk_categories_group_id_account_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
            name=op.f("fk_categories_parent_id_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_categories_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
    )
    op.create_index(
        op.f("ix_categories_group_id"), "categories", ["group_id"], unique=False
    )
    op.create_index(
        op.f("ix_categories_parent_id"), "categories", ["parent_id"], unique=False
    )
    # ### end Alembic commands ###
    op.execute(
        """
            CREATE TRIGGER trg_categories_set_updated_at
                BEFORE UPDATE ON categories
                FOR EACH ROW
                EXECUTE FUNCTION set_updated_at();
            """
    )
    op.execute(
        """
            CREATE OR REPLACE FUNCTION check_category_depth()
            RETURNS TRIGGER AS $$
            BEGIN
                IF NEW.parent_id IS NOT NULL THEN
                    IF NEW.parent_id = NEW.id THEN
                        RAISE EXCEPTION 'category_self_reference';
                    END IF;
                    IF EXISTS (
                        SELECT 1 FROM categories
                        WHERE id = NEW.parent_id AND parent_id IS NOT NULL
                    ) THEN
                        RAISE EXCEPTION 'category_max_depth_exceeded';
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
    )
    op.execute(
        """
            CREATE TRIGGER trg_check_category_depth
                BEFORE INSERT OR UPDATE ON categories
                FOR EACH ROW
                EXECUTE FUNCTION check_category_depth();
            """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_categories_parent_id"), table_name="categories")
    op.drop_index(op.f("ix_categories_group_id"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
