"""add transactions table

Revision ID: c75d7c8c91af
Revises: b1a3876a0184
Create Date: 2026-08-17 11:44:57.525089

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c75d7c8c91af"
down_revision: Union[str, Sequence[str], None] = "b1a3876a0184"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("to_account_id", sa.UUID(), nullable=True),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("transfer_group_id", sa.UUID(), nullable=True),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("income", "expense", "transfer", name="transaction_type_enum"),
            nullable=False,
        ),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("ocr_receipt_ref", sa.String(length=64), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(type = 'income' AND amount > 0) OR (type = 'expense' AND amount < 0) "
            "OR (type = 'transfer' AND amount != 0)",
            name=op.f("ck_transactions_amount_sign"),
        ),
        sa.CheckConstraint(
            "(type = 'transfer' AND to_account_id IS NOT NULL "
            "AND to_account_id != account_id) "
            "OR (type != 'transfer' AND to_account_id IS NULL)",
            name=op.f("ck_transactions_transfer_to_account"),
        ),
        sa.CheckConstraint(
            "(type = 'transfer' AND transfer_group_id IS NOT NULL) "
            "OR (type != 'transfer' AND transfer_group_id IS NULL)",
            name=op.f("ck_transactions_transfer_group"),
        ),
        sa.CheckConstraint(
            "type != 'transfer' OR category_id IS NULL",
            name=op.f("ck_transactions_transfer_no_category"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_transactions_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_transactions_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_transactions_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["to_account_id"],
            ["accounts.id"],
            name=op.f("fk_transactions_to_account_id_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_transactions_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
    )
    op.create_index(
        op.f("ix_transactions_account_id"), "transactions", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_date"), "transactions", ["date"], unique=False
    )
    op.create_index(
        "ix_transactions_transfer_group_id",
        "transactions",
        ["transfer_group_id"],
        unique=False,
        postgresql_where=sa.text("transfer_group_id IS NOT NULL"),
    )
    op.create_index(
        op.f("ix_transactions_type"), "transactions", ["type"], unique=False
    )
    # ### end Alembic commands ###
    op.execute(
        """
            CREATE TRIGGER trg_transactions_set_updated_at
                BEFORE UPDATE ON transactions
                FOR EACH ROW
                EXECUTE FUNCTION set_updated_at();
            """
    )
    op.execute(
        """
            CREATE OR REPLACE FUNCTION apply_transaction_effect(
                p_account_id UUID, p_amount BIGINT, p_sign INT
            ) RETURNS VOID AS $$
            BEGIN
                UPDATE accounts
                SET balance = balance + (p_amount * p_sign)
                WHERE id = p_account_id;
            END;
            $$ LANGUAGE plpgsql;
            """
    )
    op.execute(
        """
            CREATE OR REPLACE FUNCTION trg_transactions_balance()
            RETURNS TRIGGER AS $$
            BEGIN
                IF TG_OP = 'INSERT' THEN
                    IF NEW.deleted_at IS NULL THEN
                        PERFORM apply_transaction_effect(NEW.account_id, NEW.amount, 1);
                    END IF;
                    RETURN NEW;

                ELSIF TG_OP = 'DELETE' THEN
                    IF OLD.deleted_at IS NULL THEN
                        PERFORM apply_transaction_effect(
                            OLD.account_id, OLD.amount, -1
                        );
                    END IF;
                    RETURN OLD;

                ELSIF TG_OP = 'UPDATE' THEN
                    IF OLD.deleted_at IS NULL AND NEW.deleted_at IS NOT NULL THEN
                        PERFORM apply_transaction_effect(
                            OLD.account_id, OLD.amount, -1
                        );
                    ELSIF OLD.deleted_at IS NOT NULL AND NEW.deleted_at IS NULL THEN
                        PERFORM apply_transaction_effect(
                            NEW.account_id, NEW.amount, 1
                        );
                    ELSIF OLD.deleted_at IS NULL AND NEW.deleted_at IS NULL THEN
                        PERFORM apply_transaction_effect(
                            OLD.account_id, OLD.amount, -1
                        );
                        PERFORM apply_transaction_effect(
                            NEW.account_id, NEW.amount, 1
                        );
                    END IF;
                    RETURN NEW;
                END IF;
                RETURN NULL;
            END;
            $$ LANGUAGE plpgsql;
            """
    )
    op.execute(
        """
            CREATE TRIGGER trg_transactions_balance_update
                AFTER INSERT OR UPDATE OR DELETE ON transactions
                FOR EACH ROW
                EXECUTE FUNCTION trg_transactions_balance();
            """
    )
    op.execute(
        """
            CREATE OR REPLACE FUNCTION sync_transfer_pair()
            RETURNS TRIGGER AS $$
            BEGIN
                IF pg_trigger_depth() > 1 THEN
                    RETURN NEW;
                END IF;

                UPDATE transactions
                SET amount     = -NEW.amount,
                    date       = NEW.date,
                    notes      = NEW.notes,
                    deleted_at = NEW.deleted_at,
                    updated_by = NEW.updated_by
                WHERE transfer_group_id = NEW.transfer_group_id
                  AND id <> NEW.id;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
    )
    op.execute(
        """
            CREATE TRIGGER trg_sync_transfer_pair
                AFTER UPDATE ON transactions
                FOR EACH ROW
                WHEN (NEW.type = 'transfer')
                EXECUTE FUNCTION sync_transfer_pair();
            """
    )
    op.execute(
        """
            CREATE OR REPLACE FUNCTION check_transaction_category_group()
            RETURNS TRIGGER AS $$
            DECLARE
                v_account_group  UUID;
                v_category_group UUID;
            BEGIN
                IF NEW.category_id IS NOT NULL THEN
                    SELECT group_id INTO v_account_group
                        FROM accounts WHERE id = NEW.account_id;
                    SELECT group_id INTO v_category_group
                        FROM categories WHERE id = NEW.category_id;
                    IF v_account_group IS DISTINCT FROM v_category_group THEN
                        RAISE EXCEPTION
                            'La categoría debe pertenecer al grupo de la cuenta.';
                    END IF;
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
    )
    op.execute(
        """
            CREATE TRIGGER trg_check_transaction_category_group
                BEFORE INSERT OR UPDATE ON transactions
                FOR EACH ROW
                EXECUTE FUNCTION check_transaction_category_group();
            """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_type"), table_name="transactions")
    op.drop_index(
        "ix_transactions_transfer_group_id",
        table_name="transactions",
        postgresql_where=sa.text("transfer_group_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_transactions_date"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_account_id"), table_name="transactions")
    op.drop_table("transactions")
    # ### end Alembic commands ###
