"""add accounts table

Revision ID: ec323ec5c6fc
Revises: 439d4ea2526c
Create Date: 2026-08-14 13:24:54.707910

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec323ec5c6fc"
down_revision: Union[str, Sequence[str], None] = "439d4ea2526c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "cash",
                "bank",
                "credit_card",
                "savings",
                "investment",
                "other",
                name="account_type_enum",
            ),
            server_default=sa.text("'bank'"),
            nullable=False,
        ),
        sa.Column(
            "opening_balance",
            sa.BigInteger(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "balance", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            server_default=sa.text("'EUR'"),
            nullable=False,
        ),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_accounts_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["account_groups.id"],
            name=op.f("fk_accounts_group_id_account_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_accounts_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
    )
    op.create_index(
        op.f("ix_accounts_group_id"), "accounts", ["group_id"], unique=False
    )
    # ### end Alembic commands ###
    op.execute(
        """
            CREATE TRIGGER trg_accounts_set_updated_at
                BEFORE UPDATE ON accounts
                FOR EACH ROW
                EXECUTE FUNCTION set_updated_at();
            """
    )
    op.execute(
        """
            CREATE OR REPLACE FUNCTION init_account_balance()
            RETURNS TRIGGER AS $$
            BEGIN
                NEW.balance := NEW.opening_balance;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
    )
    op.execute(
        """
            CREATE TRIGGER trg_init_account_balance
                BEFORE INSERT ON accounts
                FOR EACH ROW
                EXECUTE FUNCTION init_account_balance();
            """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_accounts_group_id"), table_name="accounts")
    op.drop_table("accounts")
    # ### end Alembic commands ###
